languageCode = "en-us"
title = "Eric Johnson"
baseurl = "https://ericjohnsondev.github.io"
theme = "kraiklyn"

[params]
#sidebarColor = "pink"
externalTitle = " - - - External Links - - - "

[[menu.shortcuts]]
name = "Github"
url = "https://github.com/EricJohnsonDev"
weight = 20